-- Question 6: What is the total revenue generated by UrbanCart?

select
sum(oi."quantity" * p."unit_price") as "Total Revenue"
from public."FactOrderItems" oi
left join public."DimProducts" p
on oi."product_id" = p."product_id"
